# Generated by Django 4.0 on 2022-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('genres', models.CharField(choices=[('Rock', 'Rock'), ('Rap', 'Rap'), ('Pop', 'Pop'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Other', 'Other')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
