# Generated by Django 4.0 on 2022-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_song_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
