# Generated by Django 4.0 on 2022-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
