# Generated by Django 4.0 on 2022-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userstatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
